/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Segoe UI Variable"', '"Segoe UI"', '"IBM Plex Sans"', 'system-ui', 'sans-serif'],
        mono: ['"Cascadia Mono"', '"IBM Plex Mono"', '"Fira Code"', 'monospace'],
      },
      colors: {
        // Fluent UI dark theme tokens
        fluent: {
          bg:         '#0e0e0e',
          surface:    '#1a1a1a',
          surfaceAlt: '#242424',
          card:       '#2d2d2d',
          cardHover:  '#333333',
          border:     '#383838',
          borderSubtle:'#2a2a2a',
          text:       '#f0f0f0',
          textSec:    '#a0a0a0',
          textTert:   '#6a6a6a',
          accent:     '#4f6bed',
          accentHover:'#5c75f0',
          accentSubtle: 'rgba(79,107,237,0.12)',
          accentBorder: 'rgba(79,107,237,0.35)',
          success:    '#3dd54a',
          successSubtle: 'rgba(61,213,74,0.12)',
          warning:    '#fce100',
          warningBg:  'rgba(252,225,0,0.12)',
          warningBorder: 'rgba(252,225,0,0.35)',
          danger:     '#d13438',
          dangerSubtle: 'rgba(209,52,56,0.12)',
          info:       '#60cdff',
          infoSubtle: 'rgba(96,205,255,0.12)',
        },
        // Legacy aliases
        surface:  '#0e1117',
        panel:    '#161b24',
        border:   '#262d3a',
        muted:    '#4a5568',
        accent:   '#7c6fcd',
        'accent-dim': '#2d2657',
        amber:    '#f59e0b',
        'amber-dim': '#2d2200',
        teal:     '#10b981',
        'teal-dim': '#052e1c',
        danger:   '#ef4444',
      },
      borderRadius: {
        'fluent-sm': '4px',
        'fluent-md': '6px',
        'fluent-lg': '8px',
        'fluent-xl': '12px',
      },
      boxShadow: {
        'fluent-card': '0 1px 4px rgba(0,0,0,0.24), 0 0.5px 1px rgba(0,0,0,0.18)',
        'fluent-elevated': '0 4px 16px rgba(0,0,0,0.32), 0 1px 4px rgba(0,0,0,0.24)',
        'fluent-flyout': '0 8px 32px rgba(0,0,0,0.4), 0 2px 8px rgba(0,0,0,0.28)',
      },
      animation: {
        'pulse-slow': 'pulse 2.4s cubic-bezier(0.4,0,0.6,1) infinite',
        'fade-in':    'fadeIn 0.18s ease-out',
        'slide-up':   'slideUp 0.22s ease-out',
        'slide-right': 'slideRight 0.2s ease-out',
        'scale-in':   'scaleIn 0.15s ease-out',
      },
      keyframes: {
        fadeIn:  { from: { opacity: 0 }, to: { opacity: 1 } },
        slideUp: { from: { opacity: 0, transform: 'translateY(8px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
        slideRight: { from: { opacity: 0, transform: 'translateX(-8px)' }, to: { opacity: 1, transform: 'translateX(0)' } },
        scaleIn: { from: { opacity: 0, transform: 'scale(0.96)' }, to: { opacity: 1, transform: 'scale(1)' } },
      },
    },
  },
  plugins: [],
}
